name: 'Format and Post ChatGPT Response'
description: 'Formats ChatGPT response as Markdown and posts it to GitHub Discussions'
inputs:
  response:
    description: 'ChatGPT response'
    required: true
  repository-id:
    description: 'GitHub repository ID'
    required: true
  category-id:
    description: 'GitHub Discussions category ID'
    required: true
outputs:
  discussion-url:
    description: 'URL of the created discussion'
runs:
  using: 'node12'
  main: 'format-and-post.js' # The entry point script or code file
